from aiogram.dispatcher.filters.state import StatesGroup, State

class TestState(StatesGroup):
    test1 = State()
    test2 = State()
    test3 = State()
    test4 = State()
    test5 = State()
    test6 = State()
    test7 = State()
    test8 = State()
    test9 = State()
    test10 = State()
    test11 = State()
    test12 = State()
    test13 = State()
    test13_1 = State()
    test14 = State()
    test15 = State()
    test15_1 = State()
    test16 = State()
    test17 = State()
    test18 = State()
    test18_1 = State()
    test19 = State()
    test19_1 = State()
